/**
 * Generated by `scripts/gen-licences.mjs` — do not edit by hand.
 *
 * Regenerate after adding or removing a runtime dependency:
 *
 *   node scripts/gen-licences.mjs
 */

export interface UpstreamWork {
    name: string;
    url?: string;
    /** i18n key describing what this work is to the app. */
    roleKey: string;
    /** `none declared` is a real answer — see the note in the generator. */
    licence: string;
    /**
     * No LICENCE file in the repository, and none claimed. Optional because a cited
     * reference is neither licensed nor unlicensed — see `referenceOnly`.
     */
    noLicence?: boolean;
    /**
     * Permission exists by correspondence rather than by a file in the upstream
     * repository. Rendered as a note explaining the grant and its non-commercial
     * limit, because neither is visible from that repository.
     */
    granted?: boolean;
    /**
     * A cited reference, not a repository whose code was reused. Its own flag so the
     * "no LICENCE file in the repository" sentence is not applied to a website.
     */
    referenceOnly?: boolean;
    copyright?: string;
}

export interface RuntimeLicence {
    name: string;
    licence: string;
}

export const GENERATED_AT = "2026-09-22";

export const UPSTREAM_WORKS: UpstreamWork[] = [
    {
        "name": "HRT-Recorder-PKcomponent-Test",
        "url": "https://github.com/LaoZhong-Mihari/HRT-Recorder-PKcomponent-Test",
        "roleKey": "licence.upstream_algorithm",
        "licence": "non-commercial, granted",
        "noLicence": false,
        "granted": true,
        "copyright": "Copyright © Mihari."
    },
    {
        "name": "HRT-Recorder-online",
        "url": "https://github.com/LaoZhong-Mihari/HRT-Recorder-online",
        "roleKey": "licence.upstream_original",
        "licence": "none declared",
        "noLicence": true
    },
    {
        "name": "Oyama's HRT Tracker",
        "url": "https://github.com/xunxunProjects/Oyama-s-HRT-Tracker",
        "roleKey": "licence.upstream_fork",
        "licence": "MIT",
        "noLicence": false,
        "copyright": "Copyright (c) 2025 Joseph Smirnova Oyama"
    },
    {
        "name": "MtF.wiki",
        "url": "https://mtf.wiki/",
        "roleKey": "licence.reference_mtfwiki",
        "licence": "CC BY-SA 4.0",
        "referenceOnly": true,
        "copyright": "MtF.wiki contributors"
    },
    {
        "name": "Transfeminine Science",
        "url": "https://transfemscience.org/",
        "roleKey": "licence.reference_tfs",
        "licence": "all rights reserved",
        "referenceOnly": true,
        "copyright": "Aly and the other authors of Transfeminine Science"
    },
    {
        "name": "Transmtf-HRT-Tracker",
        "url": "https://github.com/TransmtfTeam/Transmtf-HRT-Tracker",
        "roleKey": "licence.upstream_pk_model",
        "licence": "MIT",
        "noLicence": false,
        "copyright": "Copyright (c) 2025 Transmtf Team"
    }
];

export const RUNTIME_LICENCES: RuntimeLicence[] = [
    {
        "name": "@types/uuid",
        "licence": "MIT"
    },
    {
        "name": "jspdf",
        "licence": "MIT"
    },
    {
        "name": "jspdf-autotable",
        "licence": "MIT"
    },
    {
        "name": "onnxruntime-web",
        "licence": "MIT"
    },
    {
        "name": "react",
        "licence": "MIT"
    },
    {
        "name": "react-dom",
        "licence": "MIT"
    },
    {
        "name": "reicon",
        "licence": "MIT"
    },
    {
        "name": "reicon-mcp",
        "licence": "MIT"
    },
    {
        "name": "tesseract.js",
        "licence": "Apache-2.0"
    },
    {
        "name": "uuid",
        "licence": "MIT"
    }
];
