/**
 * Generated by `scripts/gen-licences.mjs` — do not edit by hand.
 *
 * Regenerate after adding or removing a runtime dependency:
 *
 *   node scripts/gen-licences.mjs
 */

export interface UpstreamWork {
    name: string;
    url?: string;
    /** i18n key describing what this work is to the app. */
    roleKey: string;
    /** `none declared` is a real answer — see the note in the generator. */
    licence: string;
    noLicence: boolean;
    /**
     * Permission exists by correspondence rather than by a file in the upstream
     * repository. Rendered as a note explaining the grant and its non-commercial
     * limit, because neither is visible from that repository.
     */
    granted?: boolean;
    copyright?: string;
}

export interface RuntimeLicence {
    name: string;
    licence: string;
}

export const GENERATED_AT = "2026-09-17";

export const UPSTREAM_WORKS: UpstreamWork[] = [
    {
        "name": "HRT-Recorder-PKcomponent-Test",
        "url": "https://github.com/LaoZhong-Mihari/HRT-Recorder-PKcomponent-Test",
        "roleKey": "licence.upstream_algorithm",
        "licence": "non-commercial, granted",
        "noLicence": false,
        "granted": true,
        "copyright": "Copyright © Mihari."
    },
    {
        "name": "HRT-Recorder-online",
        "url": "https://github.com/LaoZhong-Mihari/HRT-Recorder-online",
        "roleKey": "licence.upstream_original",
        "licence": "none declared",
        "noLicence": true
    },
    {
        "name": "Oyama's HRT Tracker",
        "url": "https://github.com/xunxunProjects/Oyama-s-HRT-Tracker",
        "roleKey": "licence.upstream_fork",
        "licence": "MIT",
        "noLicence": false,
        "copyright": "Copyright (c) 2025 Joseph Smirnova Oyama"
    }
];

export const RUNTIME_LICENCES: RuntimeLicence[] = [
    {
        "name": "@types/bcryptjs",
        "licence": "MIT"
    },
    {
        "name": "@types/file-saver",
        "licence": "MIT"
    },
    {
        "name": "@types/uuid",
        "licence": "MIT"
    },
    {
        "name": "bcryptjs",
        "licence": "BSD-3-Clause"
    },
    {
        "name": "clsx",
        "licence": "MIT"
    },
    {
        "name": "file-saver",
        "licence": "MIT"
    },
    {
        "name": "jose",
        "licence": "MIT"
    },
    {
        "name": "jspdf",
        "licence": "MIT"
    },
    {
        "name": "jspdf-autotable",
        "licence": "MIT"
    },
    {
        "name": "jsqr",
        "licence": "Apache-2.0"
    },
    {
        "name": "jszip",
        "licence": "(MIT OR GPL-3.0-or-later)"
    },
    {
        "name": "prop-types",
        "licence": "MIT"
    },
    {
        "name": "qrcode.react",
        "licence": "ISC"
    },
    {
        "name": "react",
        "licence": "MIT"
    },
    {
        "name": "react-dom",
        "licence": "MIT"
    },
    {
        "name": "react-easy-crop",
        "licence": "MIT"
    },
    {
        "name": "reicon",
        "licence": "MIT"
    },
    {
        "name": "reicon-mcp",
        "licence": "MIT"
    },
    {
        "name": "tailwind-merge",
        "licence": "MIT"
    },
    {
        "name": "tesseract.js",
        "licence": "Apache-2.0"
    },
    {
        "name": "uuid",
        "licence": "MIT"
    }
];
